"""
================================================================================
Filename Normalization Patterns (DEFAULT/TEMPLATE)
================================================================================

AI-GENERATED CODE NOTICE:
This pattern library was developed with AI assistance to provide comprehensive
regex patterns for normalizing video filenames during duplicate detection.

⚠️ DO NOT EDIT THIS FILE DIRECTLY! ⚠️

This is the DEFAULT/TEMPLATE file. To customize patterns:
1. Copy this file to: filename_patterns_custom.py
2. Edit filename_patterns_custom.py with your custom patterns
3. The app will automatically use your custom file if it exists
4. Your custom file will be ignored by git (private/local only)

This separation allows you to:
- Keep your personal patterns private
- Update the default patterns from the repo without conflicts
- Have a working backup if you break your custom file

HOW TO CUSTOMIZE:
-----------------

1. Copy this file:
   Windows: copy filename_patterns.py filename_patterns_custom.py
   Linux/Mac: cp filename_patterns.py filename_patterns_custom.py

2. Edit filename_patterns_custom.py (NOT this file!)

3. Add your patterns to CUSTOM_PATTERNS section or modify existing categories

4. Restart the app

REGEX SYNTAX GUIDE:
-------------------

Basic Elements:
    \b          Word boundary (matches whole words)
    \d          Any digit (0-9)
    \w          Any word character (a-z, A-Z, 0-9, _)
    .           Any character (except newline)
    \s          Any whitespace

Quantifiers:
    *           Zero or more times
    +           One or more times
    ?           Zero or one time (optional)
    {n}         Exactly n times
    {n,m}       Between n and m times

Groups:
    (a|b|c)     Match a OR b OR c
    [abc]       Match any character in set
    [^abc]      Match any character NOT in set
    (...)       Capture group
    (?:...)     Non-capturing group

Anchors:
    ^           Start of string
    $           End of string

Examples:
    r'\b(1080p|720p)\b'              Matches "1080p" or "720p" as whole words
    r'\[\d+p\]'                      Matches [1080p], [720p], etc.
    r'\b(19|20)\d{2}\b'             Matches years 1900-2099
    r'www\.[a-z]+\.com'             Matches www.anything.com
    r'[-._]'                         Matches -, ., or _
    r'\[.*?\]'                       Matches [anything in brackets]

PATTERN MATCHING FLAGS:
----------------------
All patterns use re.IGNORECASE flag, so they match both uppercase and lowercase.

TESTING YOUR PATTERNS:
---------------------
1. Go to https://regex101.com
2. Select "Python" as the flavor
3. Paste your pattern in the regex field
4. Add test filenames in the test string area
5. Verify matches are highlighted correctly
6. Copy working pattern to this file

EXAMPLES:
--------

To remove your custom release group:
    r'\b(YourGroup|AnotherGroup)\b',

To remove specific words:
    r'\b(remove|these|words)\b',

To remove hash patterns:
    r'\[[a-f0-9]{8}\]',  # Removes [1a2b3c4d]

To remove file sizes:
    r'\b\d+(\.\d+)?(gb|mb|kb)\b',  # Removes 2.5GB, 700MB, etc.
"""

# =============================================================================
# PATTERN CATEGORIES
# =============================================================================

# Resolution & Quality
# Removes: 1080p, 720p, 4K, UHD, HD, etc.
RESOLUTION_PATTERNS = [
    r'\b(1080p|720p|480p|360p|240p|4k|2160p|8k|uhd|fhd|hd|sd|qhd)\b',
    r'\b\d{3,4}p\b',  # Any resolution like 1080p, 720p
    r'\[\d+p\]',  # [1080p]
    r'\(\d+p\)',  # (1080p)
]

# Source/Rip Type
# Removes: BluRay, WEBRip, DVDRip, etc.
SOURCE_PATTERNS = [
    r'\b(bluray|blu-ray|brrip|bdrip|dvdrip|dvd-rip|webrip|web-rip|web-dl|webdl)\b',
    r'\b(hdtv|pdtv|hdcam|cam|ts|telesync|r5|scr|screener)\b',
    r'\b(amzn|netflix|nf|hulu|hbo|disney|dsnp)\b',  # Streaming services
]

# Video Codecs
# Removes: x264, x265, HEVC, etc.
VIDEO_CODEC_PATTERNS = [
    r'\b(x264|x265|h264|h265|hevc|avc|vc-1|vc1|xvid|divx|vp9|av1)\b',
    r'\b(8bit|10bit|10-bit|8-bit)\b',
    r'\b(HDR|HDR10|HDR10\+|dolby\.vision|dv)\b',
    r'\b(hdr|sdr|rec\.2020|bt\.2020)\b',
]

# Audio Codecs & Channels
# Removes: AAC, AC3, DTS, 5.1, 7.1, etc.
AUDIO_PATTERNS = [
    r'\b(aac|ac3|eac3|e-ac3|dts|dts-hd|dts-x|truehd|mp3|flac|opus|vorbis|atmos)\b',
    r'\b(dd|ddp|dd\+)\b',  # Dolby Digital variants
    r'\b(5\.1|7\.1|2\.0|2\.1|stereo|mono)\b',  # Audio channels
    r'\b(atmos|immersive|surround)\b',
]

# Release Types & Editions
# Removes: REPACK, PROPER, Extended, Director's Cut, etc.
RELEASE_TYPE_PATTERNS = [
    r'\b(repack|proper|real\.proper|readnfo|nfofix|internal|limited|festival|retail)\b',
    r'\b(extended|unrated|remastered|theatrical|directors\.cut|dc|ultimate)\b',
    r'\b(special\.edition|anniversary|criterion|imax)\b',
    r'\b(complete|full|uncut|uncensored)\b',
]

# Release Groups
# Add your frequently seen release groups here
RELEASE_GROUP_PATTERNS = [
    r'\b(sample|rarbg|yts|yify|etrg|sparks|geckos|psychd|deflate)\b',
    r'\b(ntg|cmrg|amzn|nf|hulu|scene|p2p)\b',
    r'\b(torrent|pirate|encode|rip)\b',
    # ADD YOUR CUSTOM RELEASE GROUPS HERE:
    # r'\b(YourGroup|AnotherGroup|ThirdGroup)\b',
]

# Languages & Subtitles
# Removes: ENG, Spanish, Subtitles, etc.
LANGUAGE_PATTERNS = [
    r'\b(eng|english|esp|spanish|fra|french|ger|german|ita|italian)\b',
    r'\b(rus|russian|jpn|japanese|jap|kor|korean|chi|chinese|por|portuguese)\b',
    r'\b(multi|dual\.audio|multi\.sub|multi\.subs)\b',
    r'\b(sub|subs|subtitle|subtitles|cc|sdh|subbed|dubbed)\b',
]

# File Identifiers & Metadata
# Removes: Part1, CD1, Disc1, www.site.com, etc.
METADATA_PATTERNS = [
    r'\b(part\d+|cd\d+|disc\d+|disk\d+)\b',
    r'\bwww\.[a-z0-9]+\.[a-z]+\b',  # URLs like www.site.com
    r'\b(torrent|download|free)\b',
]

# Bracketed Content
# Removes anything in brackets, parentheses, or braces
BRACKET_PATTERNS = [
    r'\[.*?\]',  # Remove [anything]
    r'\{.*?\}',  # Remove {anything}
    r'\(.*?\)',  # Remove (anything)
]

# Years
# Removes 4-digit years from 1900-2099
YEAR_PATTERNS = [
    r'\b(19|20)\d{2}\b',  # Years like 1999, 2023
]

# Common Prefixes/Suffixes
# Removes leading articles like "The", "A", "An"
PREFIX_SUFFIX_PATTERNS = [
    r'^(the|a|an)\s+',  # Leading articles
    # r'\s+(the|a|an)$',  # Trailing articles (uncomment if needed)
]

# Separators
# Replaces separators with spaces
SEPARATOR_PATTERNS = [
    r'[-._+~]',  # Replace these with spaces
]

# =============================================================================
# CUSTOM PATTERNS
# =============================================================================
# ⚠️ To add custom patterns, copy this file to filename_patterns_custom.py
# and edit that file instead!
#
# DO NOT edit this section in this file - your changes will be lost when
# updating from the repository.

CUSTOM_PATTERNS = [
    # These are just examples - copy to filename_patterns_custom.py to use
    
    # Example: Remove specific words
    # r'\b(remove|this|word)\b',
    
    # Example: Remove hash-like patterns
    # r'\[[a-f0-9]{8}\]',  # Removes [1a2b3c4d]
    
    # Example: Remove file sizes
    # r'\b\d+(\.\d+)?(gb|mb|kb)\b',  # Removes 2.5GB, 700MB
    
    # Example: Remove CRC/hash checksums
    # r'\([a-f0-9]{8}\)',  # Removes (1A2B3C4D)
    
    # Example: Remove version numbers
    # r'\bv\d+(\.\d+)*\b',  # Removes v1.0, v2.3.1
    
    # ADD YOUR PATTERNS HERE:
]

# =============================================================================
# COMBINED PATTERN LIST
# =============================================================================

def get_all_patterns():
    """
    Returns all patterns combined into a single list.
    
    To disable a category, comment it out from this list.
    """
    return (
        RESOLUTION_PATTERNS +
        SOURCE_PATTERNS +
        VIDEO_CODEC_PATTERNS +
        AUDIO_PATTERNS +
        RELEASE_TYPE_PATTERNS +
        RELEASE_GROUP_PATTERNS +
        LANGUAGE_PATTERNS +
        METADATA_PATTERNS +
        BRACKET_PATTERNS +
        YEAR_PATTERNS +
        PREFIX_SUFFIX_PATTERNS +
        SEPARATOR_PATTERNS +
        CUSTOM_PATTERNS
    )


# =============================================================================
# PATTERN TESTING
# =============================================================================

if __name__ == "__main__":
    """
    Test your patterns by running this file directly:
    python filename_patterns.py
    """
    import re
    
    # Test filenames - add your own here
    test_filenames = [
        "Movie.Name.2023.1080p.BluRay.x264-YIFY.mp4",
        "The.Dark.Knight.2008.720p.BrRip.x264.YIFY.mp4",
        "Avengers.Endgame.2019.2160p.UHD.BluRay.x265-DEFLATE.mkv",
        "[YTS.MX] Movie Name (2023) [1080p] [WEBRip] [5.1] [YTS.MX].mp4",
        "Movie_Name_1080p_WEB-DL_DD5.1_H264-GROUP.mkv",
    ]
    
    print("=" * 70)
    print("FILENAME PATTERN TESTING")
    print("=" * 70)
    
    patterns = get_all_patterns()
    
    for filename in test_filenames:
        print(f"\nOriginal:   {filename}")
        
        # Simulate normalization
        name = filename.lower()
        for pattern in patterns:
            name = re.sub(pattern, ' ', name, flags=re.IGNORECASE)
        name = ' '.join(name.split()).strip()
        
        print(f"Normalized: {name}")
        print("-" * 70)
